### ISSUE TITLE
Wrong calculation in inverse base kinematic

### ISSUE THREAD

**Issue by ghost** [youbot/youbot_driver#1]
Dear Mr. Paulus,

there seems to be an error in your file (https://github.com/youbot/youbot_driver/blob/master/base-kinematic/FourSwedishWheelOmniBaseKinematic.cpp):

I think the calculation of the rotational component is wrong - it should be like this:
RadPerSec_FromTheta = ((config.lengthBetweenFrontAndRearWheels + config.lengthBetweenFrontWheels) / (2.0 \* config.wheelRadius)) \* angularVelocity;

I recognized this after running a trajectory which should have turned the youbot by pi/2, but the robot turned not far enough. You can also see this in the simulation using gazebo.

Yours sincerely
Benjamin Munske

**Comment by janpaulus** [comment]
Dear Mr. Munske,

thanks for the bug report. It is fixed now.

regards
Jan
