### ISSUE TITLE
Infinite "joint exceeded timeout" warning

### ISSUE THREAD

**Issue by Sekou** [youbot/youbot_driver#10]
Dear Mr. Paulus, 

During our experimentation with YouBot platform the youbot_driver was sometimes falling into "joint exceeded timeout" mode. We solved this problem by adding the following two lines at youbot/YouBotJoint.cpp at lines 452 and 488:

ClearMotorControllerTimeoutFlag clearTimeoutFlag;
setConfigurationParameter(clearTimeoutFlag);

Warnings now still occur from time to time, but robot does not hang anymore

**Comment by frederikhegger** [comment]
Can you explain a little bit more in detail in which kind of situations you encountered a "joint exceeded timeout". And what is the result? Does the base not move anymore?

**Comment by Sekou** [comment]
Only one wheel used to stop after this warning. Other wheels were operating normally, the base still was able to move. KUKA service team changed motor controller for this specific wheel but the problem still remained. 
It took usually about 1 minute of controlling the youBot from ROS via youbot_driver_ros_interface before the wheel stopped. When controlling the robot directly via youbot_driver (without ROS) the wheel was always working fine.

**Comment by frederikhegger** [comment]
That's really strange. In our labs, we have never experienced this kind of error. Do you think, it might be still a hardware issue?

**Comment by Sekou** [comment]
Well, actually we tested other youBots and they were working fine both with and without ROS. So, indeed the problem might be in the hardware. But in our case, resetting the flag in the code of 'youbot_driver ' helped to solve it.

**Comment by frederikhegger** [comment]
Okay, then we can close this issue.
