### ISSUE TITLE
Not Enough Ethercat Slaves for Youbot Manipulator

### ISSUE THREAD

**Issue by ghost** [youbot/youbot_driver#19]
Hi all,
I keep getting this error after the bringup of my robot. Help is needed urgent thank you!
![whatsapp image 2017-10-10 at 2 43 46 pm](https://user-images.githubusercontent.com/32256421/31376534-7fa02766-adcf-11e7-87b9-52a73bbe0a4f.jpeg)

**Comment by blumenthal** [comment]
Sounds to me like a problem with the Ethercat wiring. Is the manipulator plugged correctly to the base?  Could you please attach a full log file.  

Sebastian

**Comment by ghost** [comment]
Hi Sebastian,

Thank you so much. We've figured out that one of the wires was loose underneath the base after disassembling . 

Regards
Sheila

**Comment by blumenthal** [comment]
Good to hear you found the problem ;-)

Sebastian
