### ISSUE TITLE
Correct default joint names for ROS wrapper

### ISSUE THREAD

**Issue by blumenthal** [youbot/youbot_driver#2]
Hello Jan,

I propose to change the joint names for the manipulator, such that they fit to what is used within the ROS messages. Currently there is:

  JointName = ManipulatorJoint1
  JointName = ManipulatorJoint2
  ...

This should be:
JointName = arm_joint_1
JointName = arm_joint_2
...

Regards,
Sebastian

**Comment by janpaulus** [comment]
I renamed the joint names in the youbot-manipulator.cfg file.

Regards,
Jan
